const primaryOrange = "#FF6A00";
const lightOrange = "#FFF4F0";
const darkOrange = "#E55A00";
const accentBlue = "#2563EB";
const lightBlue = "#EFF6FF";
const darkBlue = "#1D4ED8";
const charcoalBlack = "#1A1A1A";
const softBlack = "#2D2D2D";
const lightGray = "#F8F9FA";
const mediumGray = "#6B7280";

// Default colors object for direct access
const colors = {
  text: charcoalBlack,
  textSecondary: softBlack,
  textMuted: mediumGray,
  background: "#FFFFFF",
  backgroundSecondary: lightGray,
  backgroundTertiary: "#F3F4F6",
  primary: primaryOrange,
  primaryLight: lightOrange,
  primaryDark: darkOrange,
  secondary: accentBlue,
  secondaryLight: lightBlue,
  secondaryDark: darkBlue,
  accent: accentBlue,
  accentLight: lightBlue,
  accentDark: darkBlue,
  border: "#E5E7EB",
  borderLight: "#F3F4F6",
  success: "#10B981",
  successDark: "#059669",
  warning: "#F59E0B",
  error: "#EF4444",
  info: accentBlue,
  tint: primaryOrange,
  tabIconDefault: "#9CA3AF",
  tabIconSelected: primaryOrange,
  shadow: "rgba(0, 0, 0, 0.1)",
  overlay: "rgba(0, 0, 0, 0.5)",
  mpesa: "#00A651", // M-Pesa green
  mpesaLight: "#E8F5E8",
  // Status colors
  pending: "#F59E0B",
  assigned: "#3B82F6",
  picked_up: "#8B5CF6",
  in_transit: "#06B6D4",
  delivered: "#10B981",
  cancelled: "#EF4444",
};

const Colors = {
  light: {
    text: charcoalBlack,
    textSecondary: softBlack,
    textMuted: mediumGray,
    background: "#FFFFFF",
    backgroundSecondary: lightGray,
    backgroundTertiary: "#F3F4F6",
    primary: primaryOrange,
    primaryLight: lightOrange,
    primaryDark: darkOrange,
    secondary: accentBlue,
    secondaryLight: lightBlue,
    secondaryDark: darkBlue,
    accent: accentBlue,
    accentLight: lightBlue,
    accentDark: darkBlue,
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    success: "#10B981",
    successDark: "#059669",
    warning: "#F59E0B",
    error: "#EF4444",
    info: accentBlue,
    tint: primaryOrange,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: primaryOrange,
    shadow: "rgba(0, 0, 0, 0.1)",
    overlay: "rgba(0, 0, 0, 0.5)",
    mpesa: "#00A651", // M-Pesa green
    mpesaLight: "#E8F5E8",
    // Status colors
    pending: "#F59E0B",
    assigned: "#3B82F6",
    picked_up: "#8B5CF6",
    in_transit: "#06B6D4",
    delivered: "#10B981",
    cancelled: "#EF4444",
  },
  dark: {
    text: "#FFFFFF",
    textSecondary: "#E5E7EB",
    textMuted: "#9CA3AF",
    background: "#111827",
    backgroundSecondary: "#1F2937",
    backgroundTertiary: "#374151",
    primary: primaryOrange,
    primaryLight: lightOrange,
    primaryDark: darkOrange,
    secondary: accentBlue,
    secondaryLight: lightBlue,
    secondaryDark: darkBlue,
    accent: accentBlue,
    accentLight: lightBlue,
    accentDark: darkBlue,
    border: "#374151",
    borderLight: "#4B5563",
    success: "#10B981",
    successDark: "#059669",
    warning: "#F59E0B",
    error: "#EF4444",
    info: accentBlue,
    tint: primaryOrange,
    tabIconDefault: "#6B7280",
    tabIconSelected: primaryOrange,
    shadow: "rgba(0, 0, 0, 0.3)",
    overlay: "rgba(0, 0, 0, 0.7)",
    mpesa: "#00A651",
    mpesaLight: "#E8F5E8",
    // Status colors
    pending: "#F59E0B",
    assigned: "#3B82F6",
    picked_up: "#8B5CF6",
    in_transit: "#06B6D4",
    delivered: "#10B981",
    cancelled: "#EF4444",
  },
};

// Safe colors function that provides fallbacks
export const safeColors = {
  // Ensure all required properties exist with fallbacks
  text: colors?.text || "#1A1A1A",
  textSecondary: colors?.textSecondary || "#2D2D2D",
  textMuted: colors?.textMuted || "#6B7280",
  background: colors?.background || "#FFFFFF",
  backgroundSecondary: colors?.backgroundSecondary || "#F8F9FA",
  backgroundTertiary: colors?.backgroundTertiary || "#F3F4F6",
  primary: colors?.primary || "#FF6A00",
  primaryLight: colors?.primaryLight || "#FFF4F0",
  primaryDark: colors?.primaryDark || "#E55A00",
  secondary: colors?.secondary || "#2563EB",
  secondaryLight: colors?.secondaryLight || "#EFF6FF",
  secondaryDark: colors?.secondaryDark || "#1D4ED8",
  accent: colors?.accent || "#2563EB",
  accentLight: colors?.accentLight || "#EFF6FF",
  accentDark: colors?.accentDark || "#1D4ED8",
  success: colors?.success || "#10B981",
  successDark: colors?.successDark || "#059669",
  error: colors?.error || "#EF4444",
  warning: colors?.warning || "#F59E0B",
  info: colors?.info || "#2563EB",
  border: colors?.border || "#E5E7EB",
  borderLight: colors?.borderLight || "#F3F4F6",
  shadow: colors?.shadow || "rgba(0, 0, 0, 0.1)",
  overlay: colors?.overlay || "rgba(0, 0, 0, 0.5)",
  tint: colors?.tint || "#FF6A00",
  tabIconDefault: colors?.tabIconDefault || "#9CA3AF",
  tabIconSelected: colors?.tabIconSelected || "#FF6A00",
  mpesa: colors?.mpesa || "#00A651",
  mpesaLight: colors?.mpesaLight || "#E8F5E8",
  // Status colors
  pending: colors?.pending || "#F59E0B",
  assigned: colors?.assigned || "#3B82F6",
  picked_up: colors?.picked_up || "#8B5CF6",
  in_transit: colors?.in_transit || "#06B6D4",
  delivered: colors?.delivered || "#10B981",
  cancelled: colors?.cancelled || "#EF4444",
};

export default colors;
export { Colors };